# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseCourse(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Course']] = 'Course'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CourseActions[_PrismaModelT]':
        from .client import get_client

        return actions.CourseActions[_PrismaModelT](client or get_client(), cls)


class BaseLesson(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Lesson']] = 'Lesson'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.LessonActions[_PrismaModelT]':
        from .client import get_client

        return actions.LessonActions[_PrismaModelT](client or get_client(), cls)


class BaseUserProgress(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserProgress']] = 'UserProgress'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserProgressActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserProgressActions[_PrismaModelT](client or get_client(), cls)


class BaseQuestion(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Question']] = 'Question'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.QuestionActions[_PrismaModelT]':
        from .client import get_client

        return actions.QuestionActions[_PrismaModelT](client or get_client(), cls)


class BaseUserExamAttempt(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserExamAttempt']] = 'UserExamAttempt'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserExamAttemptActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserExamAttemptActions[_PrismaModelT](client or get_client(), cls)


class BasePayment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Payment']] = 'Payment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PaymentActions[_PrismaModelT]':
        from .client import get_client

        return actions.PaymentActions[_PrismaModelT](client or get_client(), cls)


class BaseBlogPost(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BlogPost']] = 'BlogPost'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BlogPostActions[_PrismaModelT]':
        from .client import get_client

        return actions.BlogPostActions[_PrismaModelT](client or get_client(), cls)


class BaseAboutContent(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AboutContent']] = 'AboutContent'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AboutContentActions[_PrismaModelT]':
        from .client import get_client

        return actions.AboutContentActions[_PrismaModelT](client or get_client(), cls)


class BaseSubscriptionPlan(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SubscriptionPlan']] = 'SubscriptionPlan'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SubscriptionPlanActions[_PrismaModelT]':
        from .client import get_client

        return actions.SubscriptionPlanActions[_PrismaModelT](client or get_client(), cls)


class BaseTestimonial(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Testimonial']] = 'Testimonial'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TestimonialActions[_PrismaModelT]':
        from .client import get_client

        return actions.TestimonialActions[_PrismaModelT](client or get_client(), cls)


class BaseInterviewQuestion(_PrismaModel):
    __prisma_model__: ClassVar[Literal['InterviewQuestion']] = 'InterviewQuestion'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.InterviewQuestionActions[_PrismaModelT]':
        from .client import get_client

        return actions.InterviewQuestionActions[_PrismaModelT](client or get_client(), cls)


