# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('D:/gordon/backend/prisma/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'windows': 'C:\\Users\\USER\\.cache\\prisma-python\\binaries\\5.17.0\\393aa359c9ad4a4bb28630fb5613f9c281cde053\\node_modules\\prisma\\query-engine-windows.exe'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    user: 'actions.UserActions[models.User]'
    course: 'actions.CourseActions[models.Course]'
    lesson: 'actions.LessonActions[models.Lesson]'
    userprogress: 'actions.UserProgressActions[models.UserProgress]'
    question: 'actions.QuestionActions[models.Question]'
    userexamattempt: 'actions.UserExamAttemptActions[models.UserExamAttempt]'
    payment: 'actions.PaymentActions[models.Payment]'
    blogpost: 'actions.BlogPostActions[models.BlogPost]'
    aboutcontent: 'actions.AboutContentActions[models.AboutContent]'
    subscriptionplan: 'actions.SubscriptionPlanActions[models.SubscriptionPlan]'
    testimonial: 'actions.TestimonialActions[models.Testimonial]'
    interviewquestion: 'actions.InterviewQuestionActions[models.InterviewQuestion]'

    __slots__ = (
        'user',
        'course',
        'lesson',
        'userprogress',
        'question',
        'userexamattempt',
        'payment',
        'blogpost',
        'aboutcontent',
        'subscriptionplan',
        'testimonial',
        'interviewquestion',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set([]),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.user = actions.UserActions[models.User](self, models.User)
        self.course = actions.CourseActions[models.Course](self, models.Course)
        self.lesson = actions.LessonActions[models.Lesson](self, models.Lesson)
        self.userprogress = actions.UserProgressActions[models.UserProgress](self, models.UserProgress)
        self.question = actions.QuestionActions[models.Question](self, models.Question)
        self.userexamattempt = actions.UserExamAttemptActions[models.UserExamAttempt](self, models.UserExamAttempt)
        self.payment = actions.PaymentActions[models.Payment](self, models.Payment)
        self.blogpost = actions.BlogPostActions[models.BlogPost](self, models.BlogPost)
        self.aboutcontent = actions.AboutContentActions[models.AboutContent](self, models.AboutContent)
        self.subscriptionplan = actions.SubscriptionPlanActions[models.SubscriptionPlan](self, models.SubscriptionPlan)
        self.testimonial = actions.TestimonialActions[models.Testimonial](self, models.Testimonial)
        self.interviewquestion = actions.InterviewQuestionActions[models.InterviewQuestion](self, models.InterviewQuestion)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': 'D:/gordon/backend/prisma/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    user: 'UserBatchActions'
    course: 'CourseBatchActions'
    lesson: 'LessonBatchActions'
    userprogress: 'UserProgressBatchActions'
    question: 'QuestionBatchActions'
    userexamattempt: 'UserExamAttemptBatchActions'
    payment: 'PaymentBatchActions'
    blogpost: 'BlogPostBatchActions'
    aboutcontent: 'AboutContentBatchActions'
    subscriptionplan: 'SubscriptionPlanBatchActions'
    testimonial: 'TestimonialBatchActions'
    interviewquestion: 'InterviewQuestionBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.user = UserBatchActions(self)
        self.course = CourseBatchActions(self)
        self.lesson = LessonBatchActions(self)
        self.userprogress = UserProgressBatchActions(self)
        self.question = QuestionBatchActions(self)
        self.userexamattempt = UserExamAttemptBatchActions(self)
        self.payment = PaymentBatchActions(self)
        self.blogpost = BlogPostBatchActions(self)
        self.aboutcontent = AboutContentBatchActions(self)
        self.subscriptionplan = SubscriptionPlanBatchActions(self)
        self.testimonial = TestimonialBatchActions(self)
        self.interviewquestion = InterviewQuestionBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserCreateInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.User,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.User,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserUpdateInput,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.User,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserWhereUniqueInput,
        data: types.UserUpsertInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserUpdateManyMutationInput,
        where: types.UserWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.User,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.User,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CourseBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CourseCreateInput,
        include: Optional[types.CourseInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Course,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CourseCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Course,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CourseWhereUniqueInput,
        include: Optional[types.CourseInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Course,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CourseUpdateInput,
        where: types.CourseWhereUniqueInput,
        include: Optional[types.CourseInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Course,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CourseWhereUniqueInput,
        data: types.CourseUpsertInput,
        include: Optional[types.CourseInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Course,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CourseUpdateManyMutationInput,
        where: types.CourseWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Course,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CourseWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Course,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class LessonBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.LessonCreateInput,
        include: Optional[types.LessonInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Lesson,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.LessonCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Lesson,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.LessonWhereUniqueInput,
        include: Optional[types.LessonInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Lesson,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.LessonUpdateInput,
        where: types.LessonWhereUniqueInput,
        include: Optional[types.LessonInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Lesson,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.LessonWhereUniqueInput,
        data: types.LessonUpsertInput,
        include: Optional[types.LessonInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Lesson,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.LessonUpdateManyMutationInput,
        where: types.LessonWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Lesson,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.LessonWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Lesson,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserProgressBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserProgressCreateInput,
        include: Optional[types.UserProgressInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserProgress,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserProgressCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserProgress,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserProgressWhereUniqueInput,
        include: Optional[types.UserProgressInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserProgress,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserProgressUpdateInput,
        where: types.UserProgressWhereUniqueInput,
        include: Optional[types.UserProgressInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserProgress,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserProgressWhereUniqueInput,
        data: types.UserProgressUpsertInput,
        include: Optional[types.UserProgressInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserProgress,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserProgressUpdateManyMutationInput,
        where: types.UserProgressWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserProgress,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserProgressWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserProgress,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class QuestionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.QuestionCreateInput,
        include: Optional[types.QuestionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Question,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.QuestionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Question,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.QuestionWhereUniqueInput,
        include: Optional[types.QuestionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Question,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.QuestionUpdateInput,
        where: types.QuestionWhereUniqueInput,
        include: Optional[types.QuestionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Question,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.QuestionWhereUniqueInput,
        data: types.QuestionUpsertInput,
        include: Optional[types.QuestionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Question,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.QuestionUpdateManyMutationInput,
        where: types.QuestionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Question,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.QuestionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Question,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserExamAttemptBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserExamAttemptCreateInput,
        include: Optional[types.UserExamAttemptInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserExamAttempt,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserExamAttemptCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserExamAttempt,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserExamAttemptWhereUniqueInput,
        include: Optional[types.UserExamAttemptInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserExamAttempt,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserExamAttemptUpdateInput,
        where: types.UserExamAttemptWhereUniqueInput,
        include: Optional[types.UserExamAttemptInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserExamAttempt,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserExamAttemptWhereUniqueInput,
        data: types.UserExamAttemptUpsertInput,
        include: Optional[types.UserExamAttemptInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserExamAttempt,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserExamAttemptUpdateManyMutationInput,
        where: types.UserExamAttemptWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserExamAttempt,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserExamAttemptWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserExamAttempt,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class PaymentBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.PaymentCreateInput,
        include: Optional[types.PaymentInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Payment,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.PaymentCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Payment,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.PaymentWhereUniqueInput,
        include: Optional[types.PaymentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Payment,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.PaymentUpdateInput,
        where: types.PaymentWhereUniqueInput,
        include: Optional[types.PaymentInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Payment,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.PaymentWhereUniqueInput,
        data: types.PaymentUpsertInput,
        include: Optional[types.PaymentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Payment,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.PaymentUpdateManyMutationInput,
        where: types.PaymentWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Payment,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.PaymentWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Payment,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class BlogPostBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.BlogPostCreateInput,
        include: Optional[types.BlogPostInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.BlogPost,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.BlogPostCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.BlogPost,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.BlogPostWhereUniqueInput,
        include: Optional[types.BlogPostInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.BlogPost,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.BlogPostUpdateInput,
        where: types.BlogPostWhereUniqueInput,
        include: Optional[types.BlogPostInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.BlogPost,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.BlogPostWhereUniqueInput,
        data: types.BlogPostUpsertInput,
        include: Optional[types.BlogPostInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.BlogPost,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.BlogPostUpdateManyMutationInput,
        where: types.BlogPostWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.BlogPost,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.BlogPostWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.BlogPost,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AboutContentBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AboutContentCreateInput,
        include: Optional[types.AboutContentInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.AboutContent,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AboutContentCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.AboutContent,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AboutContentWhereUniqueInput,
        include: Optional[types.AboutContentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.AboutContent,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AboutContentUpdateInput,
        where: types.AboutContentWhereUniqueInput,
        include: Optional[types.AboutContentInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.AboutContent,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AboutContentWhereUniqueInput,
        data: types.AboutContentUpsertInput,
        include: Optional[types.AboutContentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.AboutContent,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AboutContentUpdateManyMutationInput,
        where: types.AboutContentWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.AboutContent,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AboutContentWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.AboutContent,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class SubscriptionPlanBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.SubscriptionPlanCreateInput,
        include: Optional[types.SubscriptionPlanInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.SubscriptionPlan,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.SubscriptionPlanCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.SubscriptionPlan,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.SubscriptionPlanWhereUniqueInput,
        include: Optional[types.SubscriptionPlanInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.SubscriptionPlan,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.SubscriptionPlanUpdateInput,
        where: types.SubscriptionPlanWhereUniqueInput,
        include: Optional[types.SubscriptionPlanInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.SubscriptionPlan,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.SubscriptionPlanWhereUniqueInput,
        data: types.SubscriptionPlanUpsertInput,
        include: Optional[types.SubscriptionPlanInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.SubscriptionPlan,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.SubscriptionPlanUpdateManyMutationInput,
        where: types.SubscriptionPlanWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.SubscriptionPlan,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.SubscriptionPlanWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.SubscriptionPlan,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class TestimonialBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.TestimonialCreateInput,
        include: Optional[types.TestimonialInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Testimonial,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.TestimonialCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Testimonial,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.TestimonialWhereUniqueInput,
        include: Optional[types.TestimonialInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Testimonial,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.TestimonialUpdateInput,
        where: types.TestimonialWhereUniqueInput,
        include: Optional[types.TestimonialInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Testimonial,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.TestimonialWhereUniqueInput,
        data: types.TestimonialUpsertInput,
        include: Optional[types.TestimonialInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Testimonial,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.TestimonialUpdateManyMutationInput,
        where: types.TestimonialWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Testimonial,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.TestimonialWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Testimonial,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class InterviewQuestionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.InterviewQuestionCreateInput,
        include: Optional[types.InterviewQuestionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.InterviewQuestion,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.InterviewQuestionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.InterviewQuestion,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.InterviewQuestionWhereUniqueInput,
        include: Optional[types.InterviewQuestionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.InterviewQuestion,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.InterviewQuestionUpdateInput,
        where: types.InterviewQuestionWhereUniqueInput,
        include: Optional[types.InterviewQuestionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.InterviewQuestion,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.InterviewQuestionWhereUniqueInput,
        data: types.InterviewQuestionUpsertInput,
        include: Optional[types.InterviewQuestionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.InterviewQuestion,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.InterviewQuestionUpdateManyMutationInput,
        where: types.InterviewQuestionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.InterviewQuestion,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.InterviewQuestionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.InterviewQuestion,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma