from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Course',
    'Lesson',
    'UserProgress',
    'Question',
    'UserExamAttempt',
    'Payment',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'progress': 'UserProgress',
        'attempts': 'UserExamAttempt',
        'payments': 'Payment',
    },
    'Course': {
        'lessons': 'Lesson',
    },
    'Lesson': {
        'course': 'Course',
        'progress': 'UserProgress',
    },
    'UserProgress': {
        'user': 'User',
        'lesson': 'Lesson',
    },
    'Question': {
    },
    'UserExamAttempt': {
        'user': 'User',
    },
    'Payment': {
        'user': 'User',
    },
}

# fmt: on